forum/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('naz.forum.views',
    url("forum/([0-9]+)/$", "view_forum", name="view_forum"),
    url("thread/([0-9]+).([0-9]+)/$", "view_thread", name="view_thread"),
    url("newreply/([0-9]+)/$", "new_reply", name="new_reply"),
    url("$", 'index'),
)

forum/models.py
from django.db import models
from django.contrib.auth.models import User,Group

class Profile(models.Model):
    # CHOICE TYPES
    OPT_SIG_SEP_TYPES = (
            (0,"None"),
            (1,"Horizontal Rule <hr>"),
            (2,"Dashes"),
            (3,"Em Dashes"))

    OPT_SEX_TYPES = (
            (0, "N/A"),
            (1, "Male"),
            (2, "Female"),
            (3, "~MYSTERIOUS FOURTH OPTION~"))

    user             = models.ForeignKey(User, unique=True)
    posts            = models.IntegerField(default=0, blank=False) # intentional.
    threads          = models.PositiveIntegerField()
    last_ip          = models.IPAddressField()
    last_url         = models.CharField(max_length=255)
    last_post_time   = models.DateTimeField(auto_now_add=True)
    last_view_time   = models.DateTimeField(auto_now_add=True)
    signature        = models.TextField(blank=True, default="")
    sex              = models.SmallIntegerField(choices=OPT_SEX_TYPES, default=0)

    user_image       = models.URLField(blank=True, null=True, default=None)

    # option flags
    option_enable_signatures = models.BooleanField(default=True)
    option_threads_per_page  = models.SmallIntegerField(default=30)
    option_posts_per_page    = models.SmallIntegerField(default=30)
    option_hide_email        = models.BooleanField(default=True)

    option_sig_separator     = models.SmallIntegerField(choices=OPT_SEX_TYPES, default=1)

class Category(models.Model):
    groups_whitelist = models.ManyToManyField(Group, null=True, blank=True)
    title            = models.CharField(max_length=130)
    min_power        = models.IntegerField(default=0)
    max_power        = models.IntegerField(null=True, blank=True)
    z_index          = models.PositiveIntegerField()
    is_hidden        = models.BooleanField(default=False)

class Forum(models.Model):
    category         = models.ForeignKey(Category)
    title            = models.CharField(max_length=130)
    description      = models.CharField(max_length=400)
    local_moderators = models.ManyToManyField(User, blank=True, null=True)
    z_index          = models.PositiveIntegerField()
    post_count       = models.PositiveIntegerField()
    thread_count     = models.PositiveIntegerField()
    last_post        = models.ForeignKey("Post", blank=True, null=True)
    min_power        = models.IntegerField()
    min_power_reply  = models.IntegerField()
    max_power        = models.IntegerField(null=True, blank=True)
    max_power_reply  = models.IntegerField(null=True, blank=True)

    is_hidden        = models.BooleanField(default=False, blank=True)
    is_locked        = models.BooleanField(default=False, blank=True)

class Thread(models.Model):
    user             = models.ForeignKey(User)
    forum            = models.ForeignKey(Forum)
    title            = models.CharField(max_length=150)
    replies          = models.PositiveIntegerField()
    views            = models.PositiveIntegerField()
    last_reply       = models.ForeignKey("Post", related_name="thread_last")
    is_locked        = models.BooleanField(default=False, blank=True)
    is_trashed       = models.BooleanField(default=False, blank=True)

    def __unicode__(self):
        return "%s" % self.title

class Post(models.Model):
    user             = models.ForeignKey(User)
    thread           = models.ForeignKey(Thread)
    posted           = models.DateTimeField(auto_now_add=True, auto_now=True)
    is_disemvoweled  = models.BooleanField(default=False, blank=True)
    is_deleted       = models.BooleanField(default=False, blank=True)
    is_hamtardized   = models.BooleanField(default=False, blank=True)
    smilies_disabled = models.BooleanField(default=False, blank=True)
    markup_disabled  = models.BooleanField(default=False, blank=True)
    html_disabled    = models.BooleanField(default=False, blank=True)

class PostRevision(models.Model):
    post       = models.ForeignKey(Post, related_name="revisions")
    content    = models.TextField()
    ip         = models.IPAddressField()
    rtime      = models.DateTimeField("Revision Time", auto_now_add=True)

    class Meta:
        get_latest_by = "rtime"

forum/forms.py
from django import forms
from forum.models import Post, PostRevision

class PostForm(forms.ModelForm):
	post_content = forms.CharField(widget=forms.Textarea)
	class Meta:
		model = Post
		exclude = ("user", "thread", "posted")

forum/views.py
# Create your views here.
from django.http import HttpResponse,HttpResponseRedirect
from django.template.loader import get_template
from django.template import RequestContext
from django.shortcuts import render_to_response
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User

from naz.forum.models import Forum, Category, Thread, Post, PostRevision, Profile
from naz.forum.forms  import PostForm

def index(request):
    return render_to_response("forum/default/index.html",
            {"categories": Category.objects.select_related().order_by("-z_index")},RequestContext(request))

def view_forum(request, forum_id):
    threads  = Thread.objects.filter(forum__id__exact=forum_id).select_related()[0:20]
    forum    = Forum.objects.select_related().get(pk=forum_id)
    return render_to_response("forum/default/forum_list.html",
            {"forum": forum, "threads": threads}, RequestContext(request))

def view_thread(request, thread_id, page_offset=0):
    posts    = Post.objects\
            .filter(thread__id__exact=thread_id)\
            .select_related()[0:20]

    thread   = Thread.objects\
            .select_related()\
            .get(pk=thread_id)

    forum    = Forum.objects\
            .get(pk=thread.forum_id)
    context  = RequestContext(
            request,
            {"forum": forum,
             "thread": thread,
             "posts": posts})

    template = get_template("forum/default/thread_list.html")
    try:
        return HttpResponse(template.render(context))
    finally:
        thread.views += 1
        thread.save()

def profile(request, profile_id):
    profile = Profile.objects.select_related().get(pk=1)
    return render_to_response(
            "forum/default/profile.html",
            {"profile": profile}, RequestContext(request))


@login_required
def new_reply(request, threadid):
    thread   = Thread.objects.get(pk=threadid)
    form     = PostForm(request.POST)
    posts    = Post.objects\
            .filter(thread__id__exact=threadid)\
            .order_by("-posted")[:15]\
            .select_related()
    context  = RequestContext(request,
            {"thread": thread, "form": form, "posts": posts, "errors": None})
    template = get_template("forum/default/newreply.html")
    prof = request.user.get_profile()
    if form.is_valid() and request.method == "POST":
        fields = filter(lambda x: x != "post_content", form.cleaned_data)
        fields = map(lambda x: (x,form.cleaned_data[x]), fields)
        fields.append(("user", request.user))
        fields.append(("thread", thread))
        p  = Post(**dict(fields))
        p.save()
        pr = PostRevision(
                ip=request.META["REMOTE_ADDR"],
                content=form.cleaned_data["post_content"],
                post=p)
        pr.save()
        prof.posts += 1
        prof.save()
        thread.replies += 1
        thread.save()
        return HttpResponseRedirect(
                reverse(
                    "view_thread",
                    args=[thread.id, int(round(thread.replies/20))]))

    return HttpResponse(template.render(context))

forum/templates/forum/base.html
{% extends "base.html" %}

{% block content %}
	{% block forum %}
	{% endblock forum %}
{% endblock content %}

forum/templates/forum/default/forum_list.html
{% extends "forum/base.html" %}

{% block forum %}
<table class="catbox"> {# HOORJ REUSE!!1 #}
	<tr><th colspan="5">{{forum.title}}</th></tr>
	<tr><th>Title</th><th>Started By</th><th>Replies</th><th>Views</th><th>Last Post</th></tr>
	{% for t in threads %}
	<tr><td><a href="{% url view_thread t.id 0 %}">{{ t.title }}</a></td><td>{{ t.user }}</td><td>{{ t.post_set.count }}</td><td>{{ t.views }}<td>{{ t.last_reply.user }}<br>{{ t.last_reply.posted|timesince }} ago</td></tr>
	{% endfor %}
</table>
{% endblock forum %}

forum/templates/forum/default/inc_thread_toolbox.html
<div class="toolbox thread">
	<ul>
		<li><a href="{% url new_reply forum.id %}">New Reply</a></li>
	</ul>
</div>

forum/templates/forum/default/index.html
{% extends "forum/base.html" %}

{% block forum %}
	{% for c in categories %}
		<table class="category">	
			<tr><th colspan="5">{{ c.title }}</th></tr>
			<tr>
				<th>&nbsp;</th>
				<th>Forum</th>
				<th>Threads</th>
				<th>Posts</th>
				<th>Last Post</th>
			</tr>
				{# iterate over the forums in this category #}
				{% for f in c.forum_set.all %}
					<tr>
						<td>0</td>
						<td><a href="{% url view_forum f.id %}">{{ f.title }}</a><br>{{ f.description }}</td>
						<td>{{ f.thread_count }}</td>
						<td>{{ f.post_count }}</td>
						<td>{% if f.last_post %}{{ f.last_post.user }}{% else %}NEVER!!!!!111111111{% endif %}</td>
					</tr>
				{% endfor %}
			</tr>
		</table>
	{% endfor %}
{% endblock forum %}

forum/templates/forum/default/newreply.html
{% extends "forum/base.html" %}

{% block forum %}
	<div class="catbox">
		<form action="{% url new_reply thread.id %}" name="new_reply" method="POST">
			<fieldset name="post_content">
				<legend>Post Content</legend>
				<p><label for="id_content">Content</label>{{ form.post_content }}</p>
			</fieldset>
			<fieldset name="options">
				<legend>Options</legend>
				<p><label for="id_smilies_disabled">Disable Smilies</label>{{ form.smilies_disabled }}</p>
				<p><label for="id_markup_disabled">Markup Disabled</label>{{ form.markup_disabled }}</p>
			</fieldset>
			<p><input type="submit" value="Submit"></p>
		</form>
	</div>

	<div class="catbox">
		<h1>And the rest of the thread ...</h1>
		{% for p in posts %}
		<div class="thread plist">
			<div class="plist user">{{ p.user }}</div>
			<div class="plist cont">{{ p.revisions.latest.content }}</div>
		</div>
		{% endfor %}
	</div>
{% endblock %}

forum/templates/forum/default/profile.html
{% extends "base.html" %}

{% block content %}
	<div id="profile">
		<h2>Profile for {{ profile.user.username }}</h2>
		<hr>
		<h3>Registered on: {{ profile.user.date_joined }}</h3>
		<ul>
			<li>Posts: {{ profile.posts }}</li>
			<li>Threads: {{ profile.threads }}</li>
		</ul>
	</div>
{% endblock %}

forum/templates/forum/default/thread_list.html
{% extends "forum/base.html" %}{% load cache %}

{% block forum %}
	{% include "forum/default/inc_thread_toolbox.html" %}
	<table class="category">
		<tr><th>User</th><th colspan="3">Post</th></tr>
		{% for post in posts %}
			{% with post.user as u %}
		<tr>
			<td class='ucell'>
				{% cache 3600 userbox u.id %}
					{{ u.username}}<br>
					Posts: {{ u.get_profile.posts }}<br>
					Joined: {{ u.date_joined|date:"M d, Y" }}
				{% endcache %}
			</td>
			<td class='upost'>
				<div class="toolbox">Posted on: {{ post.posted|date:"M d, Y" }} {{ post.posted|time:"H:i:s" }}</div>
				{% cache 7200 userpost post.id %}
					{{ post.revisions.latest.content }}
				{% endcache%}
			</td>
		</tr>
		 {% endwith %}
		{% endfor %}
	</table>
	{% include "forum/default/inc_thread_toolbox.html" %}
{% endblock forum %}

templates/base.html
<!DOCTYPE html>
<html>
	<head>
		<title>ZCF - {% block title %}Main{% endblock title %}</title>
		<link rel="stylesheet" href="{{ MEDIA_URL }}static/reset.css" type="text/css">
		<link rel="stylesheet" href="{{ MEDIA_URL }}static/zcf.css" type="text/css">
	</head>
	<body>
		{# <div id="header">{% block header %}{% endblock header %}</div> #}
		<div id="menu">{% include "menu.html" %}</div>
		<div id="content">{% block content %}{% endblock content %}</div>
	{% if debug %}
	<div style="clear: both;">
		{{ sql_queries|length }} queries
		<hr>
		<table><tr><th>Time</th><th>Query</th></tr>
	{% for query in sql_queries %}
	<tr><td>{{ query.time }}</td><td style='font-family: monospace;'>{{ query.sql }}</td></tr>
	{% endfor %}
		</table>
</div>
	{% endif %}
	<script type="text/javascript" src="{{ MEDIA_URL }}static/js/jquery.js"></script>
	</body>
</html>

templates/menu.html
<h1>Main</h1>
<ul>
	<li><a href="/board/">Forums</a></li>
	<li><a href="/">Main</a></li>
</ul>